// Verify the new /admin/research Lab page lands, all three tabs work,
// and the MCP-bootstrap snippet on the Settings tab carries the
// expected shape. Also probes the API contract:
//   GET  /api/research/threads (admin) → 200
//   POST /api/research/threads with a synthetic transcript → row visible
//
// Run:
//   BASE_URL=https://dev.ramboq.com npx playwright test research_page_verify.spec.js --workers=1 --project=chromium-desktop

import { test, expect } from '@playwright/test';

const BASE = process.env.BASE_URL || 'https://dev.ramboq.com';
const _AUTH_PASS = process.env.PLAYWRIGHT_PASS || 'admin1234';

async function login(page) {
  let tok = null;
  for (const u of ['ambore', 'rambo']) {
    const r = await page.request.post(`${BASE}/api/auth/login`, {
      data: { username: u, password: _AUTH_PASS },
    });
    if (r.ok()) { tok = (await r.json()).access_token; break; }
  }
  if (!tok) throw new Error(`login failed against ${BASE}`);
  await page.context().addInitScript((t) => { sessionStorage.setItem('ramboq_token', t); }, tok);
  await page.context().setExtraHTTPHeaders({ Authorization: `Bearer ${tok}` });
  return tok;
}

test(`/admin/research page loads + 3 tabs visible [${BASE}]`, async ({ page }) => {
  await login(page);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(`${BASE}/admin/research`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(3500);

  const slug = BASE.includes('dev') ? 'dev' : 'prod';

  // Page header — title chip
  await expect(page.locator('h1.page-title-chip')).toHaveText('Research');

  // Three tabs: Research / Drafts / Settings
  const tabs = page.locator('.lab-tab');
  await expect(tabs).toHaveCount(3);
  const tabLabels = await tabs.allTextContents();
  console.log('tabs:', tabLabels.map(t => t.trim()));
  expect(tabLabels.join(' ')).toMatch(/Research/i);
  expect(tabLabels.join(' ')).toMatch(/Drafts/i);
  expect(tabLabels.join(' ')).toMatch(/Settings/i);

  // Default tab — Research — should show the rail + empty main pane
  await expect(page.locator('.lab-rail')).toBeVisible();
  await expect(page.locator('.lab-main')).toBeVisible();

  await page.screenshot({ path: `test-results/research-default-${slug}.png` });
});

test(`/admin/research Settings tab → mcp.json + copy [${BASE}]`, async ({ page }) => {
  await login(page);
  await page.goto(`${BASE}/admin/research`, { waitUntil: 'networkidle' });
  await page.waitForTimeout(2500);

  // Click Settings tab
  await page.locator('.lab-tab', { hasText: 'Settings' }).click();
  await page.waitForTimeout(400);

  // Should see 4 cards (JWT / .mcp.json / Tools / Safety)
  const cards = page.locator('.lab-card');
  await expect(cards).toHaveCount(4);

  // .mcp.json card carries the snippet
  const codeBlocks = page.locator('.code-block');
  const codeTexts = await codeBlocks.allInnerTexts();
  console.log('code blocks:', codeTexts.length);
  expect(codeTexts.length).toBeGreaterThanOrEqual(2);
  // One of the blocks should be JSON containing "ramboq-research"
  const joined = codeTexts.join('\n');
  expect(joined).toMatch(/ramboq-research/);
  expect(joined).toMatch(/backend\.mcp\.kite_server/);
  expect(joined).toMatch(/RAMBOQ_TOKEN/);

  // Tools table — exactly 11 tools
  const toolRows = page.locator('.tools-table tbody tr');
  await expect(toolRows).toHaveCount(11);
  const toolTexts = await toolRows.allInnerTexts();
  console.log('tools:', toolTexts.slice(0, 3).map(t => t.split('\n')[0]).join(', '), '…');

  await page.screenshot({ path: `test-results/research-settings-${BASE.includes('dev') ? 'dev' : 'prod'}.png` });
});

test(`POST /api/research/threads + GET roundtrip [${BASE}]`, async ({ page }) => {
  const tok = await login(page);
  const headers = { Authorization: `Bearer ${tok}`, 'Content-Type': 'application/json' };

  // Create a synthetic thread
  const payload = {
    symbol: 'PWTEST',
    title: 'Playwright probe thread',
    confidence: 'neutral',
    thesis_text: 'Auto-generated by e2e — safe to delete.',
    transcript: [
      { role: 'user', content: 'Research PWTEST.' },
      { role: 'assistant', content: 'Synthetic thesis for verification only.' },
    ],
  };
  const create = await page.request.post(`${BASE}/api/research/threads`, {
    data: payload, headers,
  });
  expect(create.ok(), `create failed: ${create.status()}`).toBe(true);
  const thread = await create.json();
  expect(thread.id).toBeGreaterThan(0);
  expect(thread.symbol).toBe('PWTEST');
  expect(thread.confidence).toBe('neutral');

  // List should include it
  const list = await page.request.get(`${BASE}/api/research/threads?symbol=PWTEST`, { headers });
  expect(list.ok()).toBe(true);
  const rows = await list.json();
  expect(Array.isArray(rows)).toBe(true);
  expect(rows.some(r => r.id === thread.id)).toBe(true);

  // Cleanup
  const del = await page.request.delete(`${BASE}/api/research/threads/${thread.id}`, { headers });
  expect(del.ok() || del.status() === 204).toBe(true);
  console.log(`created+deleted thread ${thread.id}`);
});
